### ISSUE TITLE
Is there available zipped file on the drive? 

### ISSUE THREAD

**Issue by youcaiSUN** [3loi/MSP_Face#8]
Hi,

Thanks for your great work! When I ran the code, however, I got the message: "The video is not available. Continue with the next video". I wonder if there is available zipped file on the drive that I could download directly. 

Best regards.
Licai

**Comment by 3loi** [comment]
Unfortunately, some of the videos that we used for data collection are no longer available. We suggest you download the videos that are available.

**Comment by youcaiSUN** [comment]
Sorry for the late reply. I found that none of videos could be downloaded due to the Internet blocking. Could you please upload all videos in the dataset to Google Drive or OneDrive to ensure consistency and reproducibility? Thanks very much!

**Comment by AndreaVidal** [comment]
Thank you for the comment, since these videos are publicly available, the community can directly download them. We are not planning to post the videos online.

**Comment by youcaiSUN** [comment]
I got it. Thanks for your reply!
